name: 'generate-image-tag'
description: 'generates container image tag, based on github branch/tag name'

runs:
  using: 'composite'
  steps:
    - name: Create Image Tag from branch name
      if: startsWith(github.ref, 'refs/heads/release')
      shell: bash
      run: |
        set +e
        IMAGE_TAG=$(echo ${GITHUB_REF#refs/heads/release-})
        echo "$IMAGE_TAG" | grep -i '\-nightly$'
        if [ $? -ne 0 ]; then
          IMAGE_TAG="$IMAGE_TAG-nightly"
        fi
        set -e

        echo "IMAGE_TAG=$IMAGE_TAG" | tee -a $GITHUB_ENV | tee -a $GITHUB_OUTPUT
        echo "OVERRIDE_PUSHED_IMAGE=true"  | tee -a $GITHUB_ENV | tee -a $GITHUB_OUTPUT

    - name: Create Image Tag from tag
      if: startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: |
        IMAGE_TAG=$(echo ${GITHUB_REF#refs/tags/})

        echo "IMAGE_TAG=$IMAGE_TAG" | tee -a $GITHUB_ENV | tee -a $GITHUB_OUTPUT
        echo "OVERRIDE_PUSHED_IMAGE=false"  | tee -a $GITHUB_ENV | tee -a $GITHUB_OUTPUT
